<?php

namespace App\Enums;

enum ApiCode: string
{
  case AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED';
  case RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
  case VALIDATION_FAILED = 'VALIDATION_FAILED';
  case INTERNAL_ERROR = 'INTERNAL_ERROR';
  case HTTP_ERROR = 'HTTP_ERROR';
  case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
  case AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
  case LOGIN_SUCCESS = 'LOGIN_SUCCESS';
  case REGISTER_SUCCESS = 'REGISTER_SUCCESS';
  case INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN';
  case TOKEN_REFRESHED = 'TOKEN_REFRESHED';
  case FILE_UPLOADED = 'FILE_UPLOADED';
  case FILE_DELETED = 'FILE_DELETED';
}
